server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
# Activiti7 历史表创建
spring.activiti.history-level: full
spring.activiti.db-history-used: true
# 自动部署
spring.activiti.check-process-definitions: false